name: Generate a build and push to another branch

on:
  push:
    branches:
      - main # The branch name your are commit the new changes

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Greetings
        run: echo "Hello to DevOps !"

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - run: |
          sshpass -p ${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd domains && ls -l && chmod 777 {your domaine name in hostinger} && ls -l && cd {your domaine name in hostinger}/public_html && ls -l && rm -rf * && rm -rf .git && rm -rf .github && git clone https://github.com/{github_username}/{repo_name}.git .'


      # - name: Deploy to Hostinger
      #   uses: annshiv/Hostinger-deployment@v2.1
    

      # - name: Install all dependencies
      #   run: npm install

      # - name: Build
      #   run: npm run build # The build command of your project

      # - name: Push
      #   uses: s0/git-publish-subdir-action@develop

        # env:
        #   REPO: self
        #   BRANCH: build # The branch name where you want to push the assets
        #   FOLDER: build # The directory where your assets are generated
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
        #   MESSAGE: "Build: ({sha}) {msg}" # The commit message